### ISSUE TITLE
The  implementation on  BBR may be not right

### ISSUE THREAD

**Issue by SoonyangZhang** [imtiaztee/BBR-ACD_complete_NS3_implementation#2]
I  test BBR on a point to point link (4Mb,50ms delay, 200ms queue delay). And I add code the log the sending rate of a tcp connection. But the rate behavior of each flow is not the same in quic BBR.  The test result is given here (https://github.com/SoonyangZhang/BBR-ACD-complete-NS3-implementation), if you are interested.

**Comment by imtiaztee** [comment]
According to the basic principle of our implementation, if there is no packet losses due to congestion, BBR-ACD will behave similar to BBR. We found that you implemented your version of BBR using UDP, whereas we implemented BBR-ACD in TCP, based on Jain's implementation, which is already a well established one. And during our thorough investigation, it worked well in our experiments. Yes, we were also having some faulty results during the rigorous experiments, which was also observed for Jain's implementation.

It is quite impossible for us to go through your codes and fix errors in your implementation. Therefore, we would suggest to follow our implementation, which is based on TCP. And if you are implementing it for UDP, follow the key principle carefully.
